version: '3.9'

services:
  accessaid_frontend:
    container_name: accessaid_frontend
    image: accessaid_frontend:1.0.0
    build: ../AccessAid-frontend/
    ports:
      - 5173:5173
    depends_on:
      - accessaid
  accessaid:
    container_name: accessaid
    image: accessaid_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - POSTGRES_URL=jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    depends_on:
      - accessaid_db
  accessaid_db:
    container_name: accessaid_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_volumen:/var/lib/postgresql/data

volumes:
  db_volumen: {}
